export enum EachUserTypes {
	GET_EACH_USER_REQUEST = 'GET_EACH_USER_REQUEST',
	GET_EACH_USER_SUCCESS = 'GET_EACH_USER_SUCCESS',
	GET_EACH_USER_FAILURE = 'GET_EACH_USER_FAILURE',
	CLEAR_EACH_USER_LIST = 'CLEAR_EACH_USER_LIST'
}